### ISSUE TITLE
./base/configure/CONFIG: if statement should check for environment variable definition also

### ISSUE THREAD

**Issue by hanlet** [epics-base/epics-base#327]
https://github.com/epics-base/epics-base/blob/bc545242708372fd2fea15e7e1a8ae014c537ae5/configure/CONFIG#L19

If one depends on environment variables to define EPICS_BASE, this fails if the support modules configure/RELEASE
uses EPICS_BASE?=/path/to/base.  In our case, we depend on multiple versions of base in our CI/CD pipeline, and so we depend on the environment variable definition.  This modification was added after v7.0.5 and so has worked for us until our recent attempt to upgrade to v7.0.7.

We propose that the ifneq () statement have an or, to check that the environment variable is not set.

**Comment by anjohnson** [comment]
Hi Pierrick,

The `ifneq ($(origin EPICS_BASE),file)` statement that you refer to is immediately followed by these two lines:
```
    # Essential for the EPICS build system, see convertRelease.pl
    $(error EPICS_BASE must be set in a configure/RELEASE file)
```

The EPICS build system has always _strongly_ discouraged the use of environment variables for configuring builds since they are ephemeral — their value may change or even disappear the next time you build the same module. The `convertRelease.pl` script in Base/src/tools is used by the build to generate various lists or files by parsing the application's `configure/RELEASE` file(s) separately from GNUmake. It cannot pull arbitrary variables from the build environment — it wouldn't be able to tell which variables are meant for build configuration vs those that have nothing to do with it — so it needs to read the files itself and get the same values that GNUmake does. It also now has a check that `EPICS_BASE` was set in a RELEASE file BTW.

You admit that your CI system changes EPICS_BASE, so EPICS may be right not to trust it — the build system can tell from a RELEASE file's modification date whether some generated content needs rebuilding, but there are no modification dates on environment variables.

To configure a module for building without modifying its `configure/RELEASE` file, most support module RELEASE files now include a git-ignored `$(TOP)/configure/RELEASE.local` which you could generate something like this before building against a different Base version:
```
rm -f configure/RELEASE.local
echo "EPICS_BASE = $EPICS_BASE" > configure/RELEASE.local
```
We use that approach in our CI builds, see the EPICS [ci-scripts module](/epics-base/ci-scripts).

It occurs to me that the build doesn't have a truly correct idea of which RELEASE files are actually being used, although it probably could. Currently our dependency list for targets like `envPaths` assume that its dependencies can be found with `$(wildcard $(TOP)/configure/RELEASE*)`. Other files can be included by RELEASE from outside the application's configure directory, and of course that list can even be different for different targets. I may fix that some day.
