### ISSUE TITLE
UTAG inside epicsTimeStamp structure - evaluation

### ISSUE THREAD

**Issue by jerzyjamroz** [epics-base/epics-base#442]
Initially, the implementation of #397 was evaluated and ```UTAG``` is considered with the same constraints as the timestamp.

Therefore, the proposal is to insert it into the timestamp:

epicsTime.h:
```
typedef struct epicsTimeStamp {
    epicsUInt32    secPastEpoch;   /**< \brief seconds since 0000 Jan 1, 1990 */
    epicsUInt32    nsec;           /**< \brief nanoseconds within second */
    epicsUTag      utag;           /**< \brief user-defined tag */
} epicsTimeStamp;
```

Let me know your opinion. 

P.S. I am working on the ```utag``` support within mrfioc2 so depending on this answer, the code will be adjusted accordingly.

**Comment by anjohnson** [comment]
Unfortunately this change would probably break the CA client and server code, or at least make modified CA clients and servers incompatible with unmodified ones because the `dbr_time_*` structures defined in db_access.h all have an epicsTimeStamp data member. I'm not sure if those structures get copied directly to/from the network packets, but the CA network protocol doesn't have support for the utag member. Changing that protocol is hard and may be effectively impossible at this stage.
